package com.teamsea.model;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    private Integer teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.requirement
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    private String requirement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.isdelete
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher
     *
     * @return the value of course.teacher
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    public Integer getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher
     *
     * @param teacher the value for course.teacher
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    public void setTeacher(Integer teacher) {
        this.teacher = teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.requirement
     *
     * @return the value of course.requirement
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    public String getRequirement() {
        return requirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.requirement
     *
     * @param requirement the value for course.requirement
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    public void setRequirement(String requirement) {
        this.requirement = requirement == null ? null : requirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.isdelete
     *
     * @return the value of course.isdelete
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.isdelete
     *
     * @param isdelete the value for course.isdelete
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}