package com.teamsea.model;

import java.util.Date;

public class Work {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workfile.id
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workfile.name
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workfile.type
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workfile.student
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    private Integer student;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workfile.pushtime
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    private Date pushtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workfile.commit
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    private String commit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workfile.url
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workfile.score
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workfile.firstscore
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    private Integer firstscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workfile.second
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    private Integer second;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workfile.id
     *
     * @return the value of workfile.id
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workfile.id
     *
     * @param id the value for workfile.id
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workfile.name
     *
     * @return the value of workfile.name
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workfile.name
     *
     * @param name the value for workfile.name
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workfile.type
     *
     * @return the value of workfile.type
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workfile.type
     *
     * @param type the value for workfile.type
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workfile.student
     *
     * @return the value of workfile.student
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public Integer getStudent() {
        return student;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workfile.student
     *
     * @param student the value for workfile.student
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public void setStudent(Integer student) {
        this.student = student;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workfile.pushtime
     *
     * @return the value of workfile.pushtime
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public Date getPushtime() {
        return pushtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workfile.pushtime
     *
     * @param pushtime the value for workfile.pushtime
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public void setPushtime(Date pushtime) {
        this.pushtime = pushtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workfile.commit
     *
     * @return the value of workfile.commit
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public String getCommit() {
        return commit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workfile.commit
     *
     * @param commit the value for workfile.commit
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public void setCommit(String commit) {
        this.commit = commit == null ? null : commit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workfile.url
     *
     * @return the value of workfile.url
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workfile.url
     *
     * @param url the value for workfile.url
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workfile.score
     *
     * @return the value of workfile.score
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workfile.score
     *
     * @param score the value for workfile.score
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workfile.firstscore
     *
     * @return the value of workfile.firstscore
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public Integer getFirstscore() {
        return firstscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workfile.firstscore
     *
     * @param firstscore the value for workfile.firstscore
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public void setFirstscore(Integer firstscore) {
        this.firstscore = firstscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workfile.second
     *
     * @return the value of workfile.second
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public Integer getSecond() {
        return second;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workfile.second
     *
     * @param second the value for workfile.second
     *
     * @mbg.generated Wed Apr 26 01:50:18 CST 2023
     */
    public void setSecond(Integer second) {
        this.second = second;
    }
}