package com.teamsea.mapper;

import com.teamsea.model.Admin;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface AdminMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table admin
	 *
	 * @mbg.generated Sat May 06 16:20:09 CST 2023
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table admin
	 *
	 * @mbg.generated Sat May 06 16:20:09 CST 2023
	 */
	int insert(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table admin
	 *
	 * @mbg.generated Sat May 06 16:20:09 CST 2023
	 */
	Admin selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table admin
	 *
	 * @mbg.generated Sat May 06 16:20:09 CST 2023
	 */
	List<Admin> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table admin
	 *
	 * @mbg.generated Sat May 06 16:20:09 CST 2023
	 */
	int updateByPrimaryKey(Admin record);

	/**
	 * 管理员登录
	 * 
	 */
	@Select("select id,name,password from admin where name=#{name} and  password=#{password} and isdelete = 0")
	Admin adminLogin(Admin admin);

	/**
	 * 验证管理员是否存在
	 * 
	 */
	@Select("select count(id) from admin where id=#{id} and name=#{name} and isdelete = 0")
	int isExit(Admin admin);
}