package com.teamsea.mapper;

import com.teamsea.model.Class;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface ClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Wed Apr 26 01:34:40 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Wed Apr 26 01:34:40 CST 2023
     */
    int insert(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Wed Apr 26 01:34:40 CST 2023
     */
    Class selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Wed Apr 26 01:34:40 CST 2023
     */
    List<Class> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Wed Apr 26 01:34:40 CST 2023
     */
    int updateByPrimaryKey(Class record);
    
    /**
     * 伪删除
     * 
     */
    @Update("update class set isdelete = 1 where id = #{id}")
    int deleteClass(Integer id);
}