package com.teamsea.mapper;

import com.teamsea.model.Work;
import java.util.List;

public interface WorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workfile
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workfile
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    int insert(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workfile
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    Work selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workfile
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    List<Work> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workfile
     *
     * @mbg.generated Sat May 06 16:20:09 CST 2023
     */
    int updateByPrimaryKey(Work record);
}